#!/bin/bash

docker run --rm -d --name jaeger \
  -e COLLECTOR_OTLP_ENABLED=true \
  -p 4317:4317 \
  -p 16686:16686 \
  jaegertracing/all-in-one

#  -e COLLECTOR_ZIPKIN_HOST_PORT=:9411 \
#  -e SPAN_STORAGE_TYPE=cassandra \
#  -e --config-file=config.yaml \
#  -p 6832:6832/udp \
#  -p 5778:5778 \
#  -p 14250:14250 \
#  -p 14268:14268 \
#  -p 14269:14269 \
#  -p 9411:9411 \
#  -p 6831:6831/udp \
#  -p 4318:4318 \

# To see all the ports purposes see https://www.jaegertracing.io/docs/1.36/getting-started/
