/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ple.observabilityBridge;

import com.ple.util.IArrayList;
import com.ple.util.IList;

public class R {

  public static IList<RecordingHandler> handler = IArrayList.make(NullHandler.only);

}
