/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ple.observabilityBridge;

import com.ple.util.IArrayMap;
import com.ple.util.IMap;

import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Deque;
import java.util.List;

/**
 * Should only be used by a single thread. If it is needed in another thread, pass a cloned instance.
 */
public class RecordingService {

  public final List<RecordingHandler> handlers;
  public final Deque<String> contextList;
  public final Deque<Long> startTimeList;

  private RecordingService(List<RecordingHandler> handlers, Deque<String> contextList, Deque<Long> startTimeList) {
    this.handlers = handlers;
    this.contextList = contextList;
    this.startTimeList = startTimeList;
  }

  public static RecordingService make(RecordingHandler... handlers) {
    return new RecordingService(List.of(handlers), new ArrayDeque<>(), new ArrayDeque<>());
  }

  public RecordingService open(String context, IMap<String, Object> dimensions) {
    startTimeList.add(System.currentTimeMillis());
    contextList.add(context);

    for (RecordingHandler handler : handlers) {
      handler.open(this, context, dimensions);
    }

    return this;
  }

  public RecordingService open(String context, Object... dimensions) {
    return open(context, IArrayMap.make(dimensions));
  }

  public RecordingService open(String context) {
    return open(context, IArrayMap.empty);
  }

  public RecordingService close(String context, IMap<String, Object> dimensions) {
    for (RecordingHandler handler : handlers) {
      handler.close(this, context, dimensions);
    }
    startTimeList.removeLast();
    contextList.removeLast();
    return this;
  }

  public RecordingService close(String context, Object... dimensions) {
    return close(context, IArrayMap.make(dimensions));
  }

  public RecordingService close(String context) {
    return close(context, IArrayMap.empty);
  }

  public RecordingService clone() {
    return new RecordingService(new ArrayList(handlers), new ArrayDeque<>(contextList), new ArrayDeque<>(startTimeList));
  }

  public RecordingService log(int level, String base, IMap<String, Object> dimensions) {
    for (RecordingHandler handler : handlers) {
      handler.log(this, level, base, dimensions);
    }
    return this;
  }

  public RecordingService log(int level, String base, Object... dimensions) {
    return log(level, base, IArrayMap.make(dimensions));
  }

  public RecordingService log(String base, Object... dimensions) {
    return log(0, base, IArrayMap.make(dimensions));
  }

}
